HTML/CSS & JavaScript capstone project - Conference page
Nelitaa/Employment-and-Entrepreneurship-Fair-2022 pull request #2
Opened 2022-10-20 18:58 UTC by Nelitaa

**Project requirements:**

- Personalize the content of the page.
- Follow the design guidelines, including colors, typography (font face, size, and weight), and layout (composition, and space between elements)
- The pages should look almost identical to the original design. 
- Build these 2 pages: The home page and the about page.
- These pages have versions for 2 different screen sizes: Mobile: up to 768px wide and Desktop: 768px or wider.
- The home page has a link in the menu to the about page.
- The logo in the header links to the home page.
- When the user clicks the hamburger button on the header, the mobile menu appears over the page.
- The mobile menu has a close (X) button that closes the menu.
- The section "Featured speakers" has been created dynamically in JavaScript.
-  Give appropriate credit to the author in the README.

2022-10-20 22:56 UTC, cynthiainga requested changes
Hi @Nelitaa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] All linters are passing ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 
- [ ] Correct workflow ✔️ 

## Required Changes ♻️

- [ ] As required in the project you should record a video with a maximum length of 5 minutes and the video should contain:
  - a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
  - a demo of the project, showing the pages in different screen sizes.
  - a highlight about a piece of the code you find interesting or proud of making.

- [ ] Please kindly check the comments under the review for more details 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 22:56 UTC, cynthiainga commented on README.md
> +[Live Demo Link](https://nelitaa.github.io/EEFair2022.github.io)
- [ ] Please kindly make sure your project is deployed properly all pages, links, and images work as expected. I can't go to the about page I got an error `file not found`, and also some images are not loaded properly. Please kindly make sure your deployed link works well 🙃 🙃

2022-10-20 22:56 UTC, cynthiainga commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [x] Please kindly add the right license to your README file, cause when I click on the link it directs me to the page not found, kindly fix it 😉

2022-10-20 22:56 UTC, cynthiainga commented on about.html
> +          <li class="nav-bar-desktop-list"><a href="/about.html">About</a></li>
- [x] Good implementation of the nav bar, but I suggest you link your `About page` to your home page so the then users can navigate between the two pages easily 👍

2022-10-20 22:56 UTC, cynthiainga commented on about.html
> +        <a href="#presentation"><img class="logo-img" src="https://drive.google.com/uc?export=download&id=1kJyz0MXkWANEBI2fDUfR_w0omliq9Plp" alt="Employment and Entrepreneurship Fair 2022 logo"></a>
- [x] The logo in the header should be linked to the home page, please kindly links it to the home page 🙃

2022-10-20 22:56 UTC, cynthiainga commented on about.html
> +      <h1 class="header-title-about">Employment & Entrepreneurship Fair 2022</h1>
- [x]  I think it would be better if the titles are set up correctly for the best practice of HTML, like `h1, h2, h3,...` So as the title is `Employment & Entrepreneurship Fair 2022` I suggest you put your h2 into the p tag cause is a small text 🙃 🙃, the order of title should be `h1,h2,h3,h4,h5,h6` not `h2 then you put h1 after h2` for HTML best practice 😉

2022-10-20 22:56 UTC, cynthiainga commented on index.html
> +        <a href="#presentation"><img class="logo-img" src="https://drive.google.com/uc?export=download&id=1kJyz0MXkWANEBI2fDUfR_w0omliq9Plp" alt="Employment and Entrepreneurship Fair 2022 logo"></a>
- [x] The logo in the header should be linked to the home page, please kindly links it to the home page 🙃

2022-10-20 22:56 UTC, cynthiainga commented on index.html
> +      <h1 class="header-title">Employment &<br> Entrepreneurship <br> Fair 2022</h1>
- [x] The same remark about the titles, please kindly fix it 🙃 😉

2022-10-20 22:56 UTC, cynthiainga commented on index.html
> +      <h2 class="main-program-title">Main Program</h2>
- [x] As in the project requirements and in the original design this section contains five individual articles but you have only four. Please kindly add all five articles 🙃
- [x] Also Please make sure your cards have the hover border with white color so then when users click on one of the cards they can see the border 🙃 🙃 

See the example bellow

<img width="806" alt="Screen Shot 2022-10-20 at 17 14 53" src="https://user-images.githubusercontent.com/74501523/196989212-17b5fcc6-3034-494e-ab42-8fb3da732537.png">

2022-10-20 22:56 UTC, cynthiainga commented on speakers.js
> +  },
- [ ] This section contains six speakers but you have only 5, having a nice design that sticks to the original increases your chances for a job as recruiters will be checking your GitHub projects 👍 👍
- [ ] Also these section articles are organized in two columns of three articles each.

Your design

<img width="628" alt="Screen Shot 2022-10-21 at 00 18 47" src="https://user-images.githubusercontent.com/74501523/197070002-dfd0e282-babf-4bab-b8fa-32c2c7652c03.png">

Original design

<img width="971" alt="Screen Shot 2022-10-21 at 00 19 14" src="https://user-images.githubusercontent.com/74501523/197070040-c63be68b-5f38-46ed-998e-ce7b36f1966f.png">

2022-10-20 22:56 UTC, cynthiainga commented on index.html
> +        </ul
- [ ] The navbar on the desktop is divided into a top dark bar and a bottom white bar. The top short bar section has social media links, logout, and language links aligned to the right. Please kindly add it 🙃 🙃 

Your design 

<img width="986" alt="Screen Shot 2022-10-20 at 23 30 26" src="https://user-images.githubusercontent.com/74501523/197071848-d024c918-f965-42f5-ba2a-c07ce783fd10.png">

Original design 

<img width="986" alt="Screen Shot 2022-10-20 at 23 29 48" src="https://user-images.githubusercontent.com/74501523/197072011-be0b523a-db0d-4b85-94a0-eabbb5e59d7d.png">

2022-10-21 20:08 UTC, Nelitaa commented
Thank you very much for the advices, I follow all of them. This is the video that is missing [click here](https://www.loom.com/share/14165180c6e64079a8f7c0d87254eb70)

2022-10-21 21:16 UTC, tugsem approved these changes
Hi @Nelitaa , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![Alt Text](https://media.giphy.com/media/3o6Ztp6SgDdzR0XD2w/giphy.gif)
Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-10-21 21:17 UTC, merged